### ISSUE TITLE
2º Meetup do Svelte Brasil - Online

### ISSUE THREAD

**Issue by andrelmlins** [svelte-brasil/eventos#1]
Envie sua proposta comentando neste Issue!

Sugestão de template:
 
## Título da palestra:
Público alvo
Iniciante | Intermediário | Avançado
 
## Tempo previsto
(entre 15min à 50min)

## Markdown:

```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by Demysdcl** [comment]
```
**Título da palestra: Estilização dinâmica com Svelte do jeito fácil**

**Público alvo: Todos os públicos**

**Tempo previsto: 15 min**

**Nome do Palestrante: Demys Cota de Lima**

**Resumo da palestra: Dicas e exemplos de estilização dinâmicas com Svelte**

**Material (Se houver): Slide e Live Code**
```

**Comment by Demysdcl** [comment]
**Título da palestra: Estilização dinâmica com Svelte do jeito fácil**

**Público alvo: Todos os públicos**

**Tempo previsto: 15 min**

**Nome do Palestrante: Demys Cota de Lima**

**Resumo da palestra: Dicas e exemplos de estilização dinâmicas com Svelte**

**Material (Se houver): Slide e Live Code**

**Comment by ghost** [comment]
**Título da palestra:** Configuração de arquitetura de projeto e geração instantânea de componentes no Svelte

**Público alvo:** Todos os públicos

**Tempo previsto:** 15 min

**Nome do Palestrante:** Henrique Borges Rodrigues

**Resumo da palestra:** Demonstração de uma CLI para gerar código de componentes, rotas, e arquivos de configuração voltados ao Svelte

**Material (Se houver):** Slide e Live Code

**Comment by andrelmlins** [comment]
Submissão finalizada, teremos as palestras do Henrique e Demys no próximo meetup. Em breve faremos as divulgações e informaremos a data.
