### ISSUE TITLE
3º Meetup do Svelte Brasil - Online - Dia 10 de novembro

### ISSUE THREAD

**Issue by andrelmlins** [svelte-brasil/eventos#2]
Se você tem algum assunto ou projeto interessante sobre o mundo Svelte, envie sua proposta comentando neste Issue. A data será definida posteriormente a submissão das palestras.

Sugestão de template:
 
## Título da palestra:
Público alvo
Iniciante | Intermediário | Avançado
 
## Tempo previsto
(sem limite máximo ou mínimo)

## Markdown:

```
**Título da palestra:**

**Público alvo:**

**Tempo previsto:**

**Nome do Palestrante:**

**Resumo da palestra:**

**Material (Se houver):**
```

**Comment by lucianoratamero** [comment]
**Título da palestra:** Maneiras svelte de lidar com APIs

**Público alvo:** Web devs com conhecimentos básicos de requisições e promises

**Tempo previsto:** ~40 minutos

**Nome do Palestrante:** Luciano Ratamero

**Resumo da palestra:**
Svelte tem uma característica que, pra mim, se assemelha muito ao Python: a própria linguagem te guia a chegar a uma solução mais próxima da ideal pra qualquer caso de uso. No entanto, quando o problema exige soluções diferentes para cada caso, fica um pouco mais difícil achar uma abordagem única. Nessa palestra, pretendo discutir os prós e contras de diferentes maneiras Svelte para lidar com APIs, requisições e Promises.

**Material (Se houver):**

**Comment by andrelmlins** [comment]
Título da palestra: Criando biblioteca de utilitários para svelte
Público alvo: Iniciante/Intermediário

Tempo previsto: ~40 minutos

Nome do Palestrante: André Lins

Resumo da palestra:
No dia a dia utilizamos várias bibliotecas para Svelte ou Javascript com o objetivo de facilitar nosso trabalho. Bibliotecas de componentes, datas, rotas, gerenciamento de estados, entre outras, são comuns na criação de aplicações. Mas você já parou para pensar em tudo que necessita para criar bibliotecas? Quais são as dificuldades, desafios e quais artefatos são necessários para criação dessas bibliotecas? Nessa talk iremos falar sobre todo esse processo, mostrando as ferramentas necessárias e bibliotecas que facilitarão o desenvolvimento da sua primeira biblioteca para Svelte.
